import {
  Activity,
  Apple,
  Award,
  BookOpen,
  Brain,
  Briefcase,
  Coffee,
  Dumbbell,
  Flame,
  Heart,
  Home,
  Leaf,
  Moon,
  Music,
  PenTool,
  Pill,
  Smile,
  Sparkles,
  Star,
  Sun,
  Target,
  Trophy,
  Utensils,
  Wallet,
  Droplet,
  Footprints,
  GraduationCap,
  Bike,
  Bed,
  Palette,
  Code,
  Camera,
  Gamepad2,
  ShoppingCart,
  Phone,
  Plane,
  type LucideIcon,
} from "lucide-react";

/** Curated, searchable icon set for the category picker (PRD §5). */
export const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  apple: Apple,
  award: Award,
  book: BookOpen,
  brain: Brain,
  briefcase: Briefcase,
  coffee: Coffee,
  dumbbell: Dumbbell,
  flame: Flame,
  heart: Heart,
  home: Home,
  leaf: Leaf,
  moon: Moon,
  music: Music,
  pen: PenTool,
  pill: Pill,
  smile: Smile,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  target: Target,
  trophy: Trophy,
  utensils: Utensils,
  wallet: Wallet,
  droplet: Droplet,
  footprints: Footprints,
  graduation: GraduationCap,
  bike: Bike,
  bed: Bed,
  palette: Palette,
  code: Code,
  camera: Camera,
  game: Gamepad2,
  cart: ShoppingCart,
  phone: Phone,
  plane: Plane,
};

export const DEFAULT_ICON = "target";

export function getIcon(name: string): LucideIcon {
  return ICONS[name] ?? ICONS[DEFAULT_ICON];
}

export const ICON_NAMES = Object.keys(ICONS);
